server:
  port: 8081

spring:
  application:
    name: auth-service

  retry:
    maxAttempts: 3
    backoff-delay: 2000

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-registration: user-registration

clients:
  user-service:
    name: user-service
    url: http://localhost:8082

jwt:
  secret: ${jwt.secret}
  expiration: 3600000

  logging:
    level:
      org.springframework.cloud.gateway: INFO
      com.vlz: DEBUG

