server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-registration: user-registration

clients:
  user-service:
    url: http://localhost:8082

jwt:
  secret: "supersecretkeyforjwtinjobexchange"
  expiration: 3600000
