server:
  port: 8081

spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-registration: user-registration

clients:
  user-service:
    name: user-service
    url: http://localhost:8082

jwt:
  secret: "supersecretkeyforjwtinjobexchange"
  expiration: 3600000

  logging:
    level:
      org.springframework.cloud.gateway: INFO
      com.vlz: DEBUG

