server:
  port: 8081

spring:
  application:
    name: auth-service

  retry:
    maxAttempts: 3
    backoff-delay: 2000

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-registration: user-registration

  clients:
    user-service:
      name: user-service
      url: http://localhost:8082
    role-service:
      name: role-service
      url: http://localhost:8082
  logging:
    level:
      org.springframework.cloud.gateway: INFO
      com.vlz: DEBUG

  jwt:
    secret: ${secret-jwt-key}
    expiration: 3600000

